name: CI - validate, build, and push container
run-name: ${{ github.actor }} working the workflow
on: [push]

env:
    CONTAINER_TAG: returnonit.azurecr.io/returnonit/returnonit:latest   

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Dot Net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8'
      - name: Check it out
        uses: actions/checkout@v4
      - name: Install dependencies
        run: dotnet restore
      - name: Build Server
        run: dotnet build PersonalityBaseballCards.Server/PersonalityBaseballCards.Server.csproj
      - name: Build Models
        run: dotnet build PersonalityBaseballCards.Models/PersonalityBaseballCards.Models.csproj
      - name: Build Unit Tests
        run: dotnet build UnitTests/UnitTests.csproj
      - name: Run Unit Tests
        run: dotnet test  
  build:
    runs-on: ubuntu-latest
    needs: run-unit-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: returnonit.azurecr.io
          username: ${{ vars.AZURE_REGISTRY_USER }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.CONTAINER_TAG }}