name: run-unit-tests
run-name: ${{ github.actor }} running unit tests
on: [push]
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check it out
        uses: actions/checkout@v4
      - name: Setup Dot Net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8'
      - name: Build Server
        run: dotnet build PersonalityBaseballCards.Server/PersonalityBaseballCards.Server.csproj
      - name: Build Models
        run: dotnet build PersonalityBaseballCards.Models/PersonalityBaseballCards.Models.csproj
      - name: Build Unit Tests
        run: dotnet build UnitTests/UnitTests.csproj
      - name: Run Unit Tests
        run: dotnet test
          