name: run-unit-tests
run-name: ${{ github.actor }} running unit tests
on: [push]
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8'
      - run: dotnet build PersonalityBaseballCards.Server/PersonalityBaseballCards.Server.csproj
          